#ifndef SRC_UTILITIES_GLOBALDEFINES_H_
#define SRC_UTILITIES_GLOBALDEFINES_H_

//#define TUNING_PIDS

//Drive Config
#define DRIVE_X_AXIS 0
#define DRIVE_Y_AXIS 1
#define DRIVE_IMM_TURN 8
#define DRIVE_SHIFT_LOW 7
#define DRIVE_SHIFT_HIGH 6


#endif /* SRC_UTILITIES_GLOBALDEFINES_H_ */
